version: '3.8'

services:
  app:
    build: .
    container_name: portfolio-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/portfolio
      - SPRING_DATASOURCE_USERNAME=portfolio_user
      - SPRING_DATASOURCE_PASSWORD=portfolio_pass
    depends_on:
      - db
    networks:
      - spring-network

  db:
     image: postgres:15-alpine
     container_name: postgres-db
     ports:
       - "5432:5432"
     environment:
       - POSTGRES_DB=portfolio
       - POSTGRES_USER=portfolio_user
       - POSTGRES_PASSWORD=portfolio_pass
     volumes:
       - postgres-data:/var/lib/postgresql/data
     networks:
       - spring-network

networks:
  spring-network:
    driver: bridge

volumes:
   postgres-data: